/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        satoshi: ["Satoshi", "sans-serif"],
        cabinet: ["Cabinet Grotesk", "sans-serif"],
        dancing: ["Dancing Script", "sans-serif"],
        spacemono: ["Space Mono", "monospace"],
        zodiak: ["Zodiak", "serif"],
      },
      colors: {
        rosePine: {
          base: "#191724",
          surface: "#1f1d2e",
          overlay: "#26233a",
          muted: "#6e6a86",
          subtle: "#908caa",
          text: "#e0def4",
          love: "#eb6f92",
          gold: "#f6c177",
          rose: "#ebbcba",
          pine: "#31748f",
          foam: "#9ccfd8",
          iris: "#c4a7e7",
          highlightLow: "#21202e",
          highlightMed: "#403d52",
          highlightHigh: "#524f67",
        },
        rosePineDawn: {
          base: "#faf4ed",
          surface: "#fffaf3",
          overlay: "#f2e9e1",
          muted: "#9893a5",
          subtle: "#797593",
          text: "#575279",
          love: "#b4637a",
          gold: "#ea9d34",
          rose: "#d7827e",
          pine: "#286983",
          foam: "#56949f",
          iris: "#907aa9",
          highlightLow: "#f4ede8",
          highlightMed: "#dfdad9",
          highlightHigh: "#cecacd",
        },
      },
    },
  },
  typography: ({ theme }) => ({
    pink: {
      css: {
        '--tw-prose-body': '#000000',
        '--tw-prose-headings': theme('colors.pink[900]'),
        '--tw-prose-lead': theme('colors.pink[700]'),
        '--tw-prose-links': theme('colors.pink[900]'),
        '--tw-prose-bold': theme('colors.pink[900]'),
        '--tw-prose-counters': theme('colors.pink[600]'),
        '--tw-prose-bullets': theme('colors.pink[400]'),
        '--tw-prose-hr': theme('colors.pink[300]'),
        '--tw-prose-quotes': theme('colors.pink[900]'),
        '--tw-prose-quote-borders': theme('colors.pink[300]'),
        '--tw-prose-captions': theme('colors.pink[700]'),
        '--tw-prose-code': theme('colors.pink[900]'),
        '--tw-prose-pre-code': theme('colors.pink[100]'),
        '--tw-prose-pre-bg': theme('colors.pink[900]'),
        '--tw-prose-th-borders': theme('colors.pink[300]'),
        '--tw-prose-td-borders': theme('colors.pink[200]'),
        '--tw-prose-invert-body': theme('colors.pink[200]'),
        '--tw-prose-invert-headings': theme('colors.white'),
        '--tw-prose-invert-lead': theme('colors.pink[300]'),
        '--tw-prose-invert-links': theme('colors.white'),
        '--tw-prose-invert-bold': theme('colors.white'),
        '--tw-prose-invert-counters': theme('colors.pink[400]'),
        '--tw-prose-invert-bullets': theme('colors.pink[600]'),
        '--tw-prose-invert-hr': theme('colors.pink[700]'),
        '--tw-prose-invert-quotes': theme('colors.pink[100]'),
        '--tw-prose-invert-quote-borders': theme('colors.pink[700]'),
        '--tw-prose-invert-captions': theme('colors.pink[400]'),
        '--tw-prose-invert-code': theme('colors.white'),
        '--tw-prose-invert-pre-code': theme('colors.pink[300]'),
        '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
        '--tw-prose-invert-th-borders': theme('colors.pink[600]'),
        '--tw-prose-invert-td-borders': theme('colors.pink[700]'),
      },
    },
  }),
  plugins: [
    require("@tailwindcss/typography"),
  ],
};
